apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: fiapx
  labels:
    app.kubernetes.io/name: notifier
    app.kubernetes.io/component: notification-service
    app.kubernetes.io/part-of: fiapx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: notifier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notifier
        app.kubernetes.io/component: notification-service
        app.kubernetes.io/part-of: fiapx
    spec:
      enableServiceLinks: false
      containers:
        - name: notifier
          image: fiapx-notifier:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: fiapx-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fiapx-secrets
                  key: DATABASE_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: fiapx-secrets
                  key: RABBITMQ_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
