apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: fiapx
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/component: email-dev
    app.kubernetes.io/part-of: fiapx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mailhog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mailhog
        app.kubernetes.io/component: email-dev
        app.kubernetes.io/part-of: fiapx
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog
          ports:
            - containerPort: 1025
              protocol: TCP
              name: smtp
            - containerPort: 8025
              protocol: TCP
              name: web
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
