apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: fiapx
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/component: video-worker
    app.kubernetes.io/part-of: fiapx
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worker
        app.kubernetes.io/component: video-worker
        app.kubernetes.io/part-of: fiapx
    spec:
      enableServiceLinks: false
      containers:
        - name: worker
          image: jocosta96/video-processing-worker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: fiapx-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fiapx-secrets
                  key: DATABASE_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: fiapx-secrets
                  key: RABBITMQ_URL
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fiapx-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fiapx-secrets
                  key: MINIO_SECRET_KEY
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
